# -*- coding: utf-8 -*-
"""basic_segmentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZJv5yGJqNsqP8OXMLjOG1UxUNs-P92T
"""

import cv2
import numpy as np

image = cv2.imread('snow_example.png')
original = image.copy()

hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

lower_white = np.array([0, 0, 200])  # H, S, V
upper_white = np.array([180, 50, 255])

mask = cv2.inRange(hsv, lower_white, upper_white)

kernel = np.ones((7, 7), np.uint8)

mask_cleaned = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)  # 작은 흰색 점
mask_cleaned_2 = cv2.morphologyEx(mask_cleaned, cv2.MORPH_CLOSE, kernel)  # 작은 검은 구멍

cv2.imshow("Original Image", original)
cv2.imshow("Mask - Improved", mask_cleaned_2)

cv2.waitKey(0)
cv2.destroyAllWindows()